ead:
  serviceRegistry:
    username: serviceregistryprod
    password: 'z9A6EYC4GC'
  auth:
    jwtSecret: 'w3owMA9W2TCbvmnI8jaVtB0CWqtoFZHYmaZ3n7upTgF3DkrMcvJa96d1Fr9HwvgBKIYWI98URG1wqvQDEdXNCe3XqEu32DsEIfbwWncMEujBBJ46K3xeeW8WGyk16gyi'
    jwtExpirationMs: 14400000

eureka:
  client:
    serviceUrl:
      defaultZone: 'https://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@eadmarcio-serviceregistry-prod-e0ff66cfb8cf.herokuapp.com/eureka'
  instance:
    hostname: ${APP_DOMAIN_NAME}
    non-secure-port: 80