server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-course-v2
    username: postgres
    password: 1234
    
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always
  rabbitmq:
    addresses: amqps://xjyrnwad:xZz_ThHPUML9QEzB8ZLRc2yv2bVydR8p@jackal.rmq.cloudamqp.com/xjyrnwad


logging:
  level:
    com.ead: INFO
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'
  broker:
    exchange:
      userEventExchange: ead.userevent
      notificationCommandExchange: ead.notificationcommand
    queue:
      userEventQueue:
        name: ead.userevent.ms.course
    key:
      notificationCommandKey: ms.notification
        
management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health