server:
  port: 8084
  servlet:
    context-path: '/ead-notification-hex/'

spring:
  application:
    name: ead-notification-service-hex
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-notification-hex
    username: postgres
    password: 1234
    
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always
  rabbitmq:
    addresses: amqps://xjyrnwad:xZz_ThHPUML9QEzB8ZLRc2yv2bVydR8p@jackal.rmq.cloudamqp.com/xjyrnwad
  
  
logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO
ead:
  broker:
    exchange:
      notificationCommandExchange: ead.notificationcommand
    queue:
      notificationCommandQueue:
        name: ead.notificationcommand.ms.notification
    key:
      notificationCommandKey: ms.notification
     